[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
ffi = true
fs_permissions = [{ access = "read", path = "./img/"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config̦

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/68a1N5XFCnNDReCEqXIakin9Ae08KWuN"